### PR TITLE
Board coordinates

### PR DESCRIPTION
**Pull request by acristescu**
@popz73 FYI, this what I am suggesting to do. Comments are welcome.

### CODE REVIEW

**Comment by acristescu** [comment]
I'm merging this now since I want to publish the new version. Please feel free to comment if so inclined, we'll address any issues in a new commit.

**Comment by popz73** [comment]
Hi, everything looks good, I understand the changes and it's nice to see them implemented to get what you expect (I'm a C++ guy that never touched Kotlin/mobile before :P)

Just one comment - you removed the bold typeface, right? I had set it as bold after playing a few days with/without the bold typeface - especially in the "busy" (with grain) board background we have, I am distracted by the difficulty to read the non-bold one which is not that discernible.
It's common (e.g. Pandanet) to have it in bold and I think it works better here. What led you to go for the non-bold one?

**Comment by acristescu** [comment]
I've played with it on and off for a while too and I found it a bit overbearing, particularily on the 9x9 board. At one point, I even had it bolded only on the 19x19 board. I ended up making it regular fontface but instead increasing the size of space allocated to the letters (and the font size).

The bootom line is that I do not want to have the coordinates clutter the screen anymore (a 19x19 board is already intimidating to a beginner) and so the less conspicuous they are, the better. If you really have to read them (because somebody posted something in the chat for example) you can, but they don't jump at you when you're not interested.

It looks OK to me now, but the thing is though I can only judge it on my personal phone (S9+) which is quite a large one.  Perhaps on smaller devices it's worse. Just how bad do they look to you?

**Comment by popz73** [comment]
My Mi A1 is not much smaller, but here's a SS:
Screenshot_20190328-220730

I really feel more distracted with this - the letters are so thin that my attention tends to go to them to read then clearly (e.g. the 'M').
I preferred the previous setup with shorter fonts but legible and slimmer borders - as weird as it may seem they disappear from my attention much better.

I do only play in 19x19 though - if the motivation to go bigger/non-bold was mainly the aspect.of the 9x9 board, having it as bold on 19x19 could be a good option.

**Pull request merged**
