### PR TITLE
feat: show game time like on OGS

### LINKED ISSUE #72: Feature request: more detailed units for time remaining
Please could we have a small tweak to how remaining time is displayed? For ladder games (increment measured in days) Xd Yh for durations > 1 day, not just Xd like now.

More generally, I think the principle should be to show duration measured in two units: the main unit of interest and the next smaller unit. So if the increments are in weeks, show Xw Yd. Does that make sense?

Thanks.

### PR DESCRIPTION
**Pull request by v011**
Resolves #72

Simulation of time displayed on OGS.

Examples of time values with these new changes :

```
23h 59m
24h
25h
47h
48h
2 day 1 hour
2 day 23 hours
3 days
3 days 1 hour
6 days 23 hours
1 week
1 week 1 day
3 weeks 6 days
4 weeks
```

### CODE REVIEW

**Comment by DrewHeath** [comment]
Excellent! Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by acristescu** [comment]
Hi @v011 , thank you for the contribution. As I cannot test it right now, can you please confirm that you have checked that the new strings are not too long and breaking the layout on smaller screen devices? I remember this being a problem when I first wrote this (many years ago) and I see that some of the strings are at least twice as long as the longest one I used to have: compare `6 days 23 hours` with `4 weeks`.

**Comment by DrewHeath** [comment]
Perhaps d for days and hr for hours would be better.

**Comment by v011** [comment]
I also though that some of the strings could be too long, but I preferred, as first suggestion, to stick on the current OGS game time formats and see what do you think about that.

Here is an alternative display. Maybe, it would be better for smaller screen devices. The longest string here is `23h 59m` (7 chars).

```
23h 59m
24h
25h
47h
48h
1d 1h
1d 23h
2d
2d 1h
6d 23h
1w
1w 1d
3w 6d
4w
```

@acristescu , unfortunately, I don't know how to test all the app, I'm not an Android developer. If you've some time to check, could you tell me if I have to adapt the format if it's too long.

**Review by acristescu — APPROVED** [review]
Approved pending testing of max length strings

**Comment by acristescu** [comment]
Without any further changes it looks like the screenshots below. It's not *that* bad, we could definitely adjust the layouts to allow for these longer strings, but I still think I'd prefer more condensed strings just so that there is not too much of a difference between where the icons are on screen. For example, in the game screenshot below one player has 4 weeks while the other has 1 week 5 days. The icons are in different places since the space required is different.

What do you guys think would be the better solution? Shorten the string (my preferred solution) or make the icon space unequal to accommodate potentially longer strings?

@v011 @DrewHeath @teapoweredrobot


Screenshot_1611494188
Screenshot_1611494195

**Comment by popz73** [comment]
short string for me, no value in 'weeks' and 'days' compared to 'w' 'd'
unless they fit.
Let's say that the maximum length is 10 chars, an idea would be to shorten
from left to right until the length is OK, like

1 w 2 days
1 week
2 days
1 d 17 h
1 d 1 hour

**Comment by alexmitrani** [comment]
The icons could be potentially be replaced with text labels: "score:" and "time:"
On the dark theme the score icon is invisible anyway.

**Comment by acristescu** [comment]
> The icons could be potentially be replaced with text labels: "score:" and "time:"

Would that make any difference though? Text or icon, it's still going to be uneven between the two players

> On the dark theme the score icon is invisible anyway.

That's been fixed already, but it's not released because @bitrise has some gremlins (I've contacted their tech support, they're taking their sweet time responding).

**Comment by v011** [comment]
It seems there is enough space to fit long strings. Personally, it doesn't really matter for me if we choose the long or short version. I just wonder how a beginner would interpret when (s)he sees "3d" (or "3 d"). At the beginning, one could wonder if it means "3 dan", "3 days" or something else, despite the fact that there is a label or an icon. I hope the short version wouldn't be confusing for these people.
Also, I prefer not mixing long and short strings.

**Comment by acristescu** [comment]
I went with a mix of long and short names to make them fit. I gave up on using weeks and instead just say the number of days when it's >7 (e.g. `23 days` instead of `3 weeks 2 days`). I'll cut a release today if the Bitrise Gods are willing to cooperate.

**Comment by v011** [comment]
Dropping the number of weeks is more consistent regarding how OGS displays remaining time.

**Pull request merged**
