### PR TITLE
Add a better README

### PR DESCRIPTION
**Pull request by hadim**
I am also considering adding [Travis](https://docs.travis-ci.com/user/languages/android/) support so each commit would be tested. What do you think?

### CODE REVIEW

**Comment by hadim** [comment]
Travis support is taking a good way. Now stuck at the same building error as here: https://github.com/acristescu/OnlineGo/issues/24

**Comment by acristescu** [comment]
Bitrise is already integrated :) sorry I'm on vacation now, will chat more when back

**Comment by hadim** [comment]
I think Travis is more powerful and transparent than Bitrise for few reasons:

- It's impossible to see the build logs ([for example](https://www.bitrise.io/build/e17d2c858943cd8e)) without being login. I don't like that since it makes it less transparent for people who want to contribute without having yet-another-CI-account (only the owner needs to subscribe to Travis).

- I don't see any [`.travis.yml` equivalent file](https://github.com/hadim/OnlineGo/blob/722454a097885bff2b5df4d6273b16f3654e5a4e/.travis.yml) for Bitrise. This file is very important to make the build process reproducible and transparent to everyone. It's also more flexible as you can automatically deploy releases to Github 9among other things).

- The free version of Bitrise is limited to 200 builds per month... if the development increases we could this limit very quickly. Travis for open source projects is totally free.

As for the `google-services.json` file, if you decide to commit it to the repo, everything is good. If don't we can still encrypt it, so Travis can use it safely.

**Comment by acristescu** [comment]
Although you make some fair points (e.g. public logs is a feature in closed beta ATM for bitrise) I still don't think that fixing something that is working well enough (e.g. CI integration) is what we want to do right now. There is overhead in migrating to Travis: for example, I have it setup so simply fast-forward merging onto the release branch does everything needed for a release, including signing with the proper keys and uploading to google playstore without any human intervention. I know you can do this with travis too, but would take several hours to get right (including ensuring the version code does not conflict) and those are some hours that would be better spend doing something else (e.g. chat, tutorial, better handling of move submission over bad connection).

That being said, there are some interesting ideas in the PR: having a debug google-services.json that gets overwritten by the CI scripts for release builds might work. Btw, if you read carefully, the link you posted for the google group discussion does mention that the google-services.json should not be pushed for open-source projects :)

We do need a better Readme that's for sure, but linking that PR to the Travis integration is not a good idea IMHO...

**Comment by acristescu** [comment]
Btw, there is the possibility of having the `bitrise.yml` (the equivalent of `.travis.yml`) live in the github repo, which, as you point out, is good for the reproducibility of the builds.

**Pull request closed without merging**
